# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directories:
      - "/HomeScreen.Web/HomeScreen.Web.Components/homescreen.web.components.client/"
      - "/HomeScreen.Web/HomeScreen.Web.Dashboard/homescreen.web.dashboard.client/"
      - "/HomeScreen.Web/HomeScreen.Web.Slideshow/homescreen.web.slideshow.client/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directories:
      - "HomeScreen.AppHost"
      - "HomeScreen.Database/HomeScreen.Database.MediaDb"
      - "HomeScreen.Database/HomeScreen.Database.MediaDb.Migrations"
      - "HomeScreen.ServiceDefaults"
      - "HomeScreen.Services/HomeScreen.Service.Media"
      - "HomeScreen.Services/HomeScreen.Service.Media.UnitTests"
      - "HomeScreen.Services/HomeScreen.Service.MediaClient"
      - "HomeScreen.Services/HomeScreen.Service.Proto"
      - "HomeScreen.Services/HomeScreen.Service.Weather"
      - "HomeScreen.Web/HomeScreen.Web.Dashboard/HomeScreen.Web.Dashboard.Server"
      - "HomeScreen.Web/HomeScreen.Web.Dashboard/HomeScreen.Web.Slideshow.Server"
    schedule:
      interval: "weekly"
