---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homescreen-web-slideshow
  labels:
    app: homescreen-web-slideshow
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: homescreen-web-slideshow
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: homescreen-web-slideshow
    spec:
      containers:
      - name: homescreen-web-slideshow
        image: localhost:32000/home-screen/homescreen-web-slideshow:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: homescreen-web-slideshow-env
      terminationGracePeriodSeconds: 180