/*
 * Nominatim Open API Spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: blake.rogan@outlook.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HomeScreen.OpenAPI.Nominatim.Model;
using HomeScreen.OpenAPI.Nominatim.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HomeScreen.OpenAPI.Nominatim.Test.Model
{
    /// <summary>
    ///  Class for testing NumberBoolean
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NumberBooleanTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NumberBoolean
        //private NumberBoolean instance;

        public NumberBooleanTests()
        {
            // TODO uncomment below to create an instance of NumberBoolean
            //instance = new NumberBoolean();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NumberBoolean
        /// </summary>
        [Fact]
        public void NumberBooleanInstanceTest()
        {
            // TODO uncomment below to test "IsType" NumberBoolean
            //Assert.IsType<NumberBoolean>(instance);
        }
    }
}
