/*
 * Nominatim Open API Spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: blake.rogan@outlook.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HomeScreen.OpenAPI.Nominatim.Model;
using HomeScreen.OpenAPI.Nominatim.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HomeScreen.OpenAPI.Nominatim.Test.Model
{
    /// <summary>
    ///  Class for testing OutputFormat
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutputFormatTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OutputFormat
        //private OutputFormat instance;

        public OutputFormatTests()
        {
            // TODO uncomment below to create an instance of OutputFormat
            //instance = new OutputFormat();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OutputFormat
        /// </summary>
        [Fact]
        public void OutputFormatInstanceTest()
        {
            // TODO uncomment below to test "IsType" OutputFormat
            //Assert.IsType<OutputFormat>(instance);
        }
    }
}
