/*
 * Nominatim Open API Spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: blake.rogan@outlook.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HomeScreen.OpenAPI.Nominatim.Model;
using HomeScreen.OpenAPI.Nominatim.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HomeScreen.OpenAPI.Nominatim.Test.Model
{
    /// <summary>
    ///  Class for testing ReverseOutputXmlResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReverseOutputXmlResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReverseOutputXmlResult
        //private ReverseOutputXmlResult instance;

        public ReverseOutputXmlResultTests()
        {
            // TODO uncomment below to create an instance of ReverseOutputXmlResult
            //instance = new ReverseOutputXmlResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReverseOutputXmlResult
        /// </summary>
        [Fact]
        public void ReverseOutputXmlResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReverseOutputXmlResult
            //Assert.IsType<ReverseOutputXmlResult>(instance);
        }

        /// <summary>
        /// Test the property 'PlaceId'
        /// </summary>
        [Fact]
        public void PlaceIdTest()
        {
            // TODO unit test for the property 'PlaceId'
        }

        /// <summary>
        /// Test the property 'OsmType'
        /// </summary>
        [Fact]
        public void OsmTypeTest()
        {
            // TODO unit test for the property 'OsmType'
        }

        /// <summary>
        /// Test the property 'OsmId'
        /// </summary>
        [Fact]
        public void OsmIdTest()
        {
            // TODO unit test for the property 'OsmId'
        }

        /// <summary>
        /// Test the property 'Lat'
        /// </summary>
        [Fact]
        public void LatTest()
        {
            // TODO unit test for the property 'Lat'
        }

        /// <summary>
        /// Test the property 'Lon'
        /// </summary>
        [Fact]
        public void LonTest()
        {
            // TODO unit test for the property 'Lon'
        }

        /// <summary>
        /// Test the property 'Boundingbox'
        /// </summary>
        [Fact]
        public void BoundingboxTest()
        {
            // TODO unit test for the property 'Boundingbox'
        }

        /// <summary>
        /// Test the property 'PlaceRank'
        /// </summary>
        [Fact]
        public void PlaceRankTest()
        {
            // TODO unit test for the property 'PlaceRank'
        }

        /// <summary>
        /// Test the property 'AddressRank'
        /// </summary>
        [Fact]
        public void AddressRankTest()
        {
            // TODO unit test for the property 'AddressRank'
        }
    }
}
