/*
 * Nominatim Open API Spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: blake.rogan@outlook.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HomeScreen.OpenAPI.Nominatim.Model;
using HomeScreen.OpenAPI.Nominatim.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HomeScreen.OpenAPI.Nominatim.Test.Model
{
    /// <summary>
    ///  Class for testing ReverseOutputJson
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReverseOutputJsonTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReverseOutputJson
        //private ReverseOutputJson instance;

        public ReverseOutputJsonTests()
        {
            // TODO uncomment below to create an instance of ReverseOutputJson
            //instance = new ReverseOutputJson();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReverseOutputJson
        /// </summary>
        [Fact]
        public void ReverseOutputJsonInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReverseOutputJson
            //Assert.IsType<ReverseOutputJson>(instance);
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
    }
}
