/*
 * Nominatim Open API Spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: blake.rogan@outlook.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HomeScreen.OpenAPI.Nominatim.Model;
using HomeScreen.OpenAPI.Nominatim.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HomeScreen.OpenAPI.Nominatim.Test.Model
{
    /// <summary>
    ///  Class for testing ReverseOutputXml
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReverseOutputXmlTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReverseOutputXml
        //private ReverseOutputXml instance;

        public ReverseOutputXmlTests()
        {
            // TODO uncomment below to create an instance of ReverseOutputXml
            //instance = new ReverseOutputXml();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReverseOutputXml
        /// </summary>
        [Fact]
        public void ReverseOutputXmlInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReverseOutputXml
            //Assert.IsType<ReverseOutputXml>(instance);
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

        /// <summary>
        /// Test the property 'Querystring'
        /// </summary>
        [Fact]
        public void QuerystringTest()
        {
            // TODO unit test for the property 'Querystring'
        }

        /// <summary>
        /// Test the property 'Attribution'
        /// </summary>
        [Fact]
        public void AttributionTest()
        {
            // TODO unit test for the property 'Attribution'
        }

        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }

        /// <summary>
        /// Test the property 'Addressparts'
        /// </summary>
        [Fact]
        public void AddresspartsTest()
        {
            // TODO unit test for the property 'Addressparts'
        }
    }
}
