/*
 * Nominatim Open API Spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: blake.rogan@outlook.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = HomeScreen.OpenAPI.Nominatim.Client.FileParameter;
using OpenAPIDateConverter = HomeScreen.OpenAPI.Nominatim.Client.OpenAPIDateConverter;

namespace HomeScreen.OpenAPI.Nominatim.Model
{
    /// <summary>
    /// Defines Layer
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Layer
    {
        /// <summary>
        /// Enum Address for value: address
        /// </summary>
        [EnumMember(Value = "address")]
        Address,

        /// <summary>
        /// Enum Poi for value: poi
        /// </summary>
        [EnumMember(Value = "poi")]
        Poi,

        /// <summary>
        /// Enum Railway for value: railway
        /// </summary>
        [EnumMember(Value = "railway")]
        Railway,

        /// <summary>
        /// Enum Natural for value: natural
        /// </summary>
        [EnumMember(Value = "natural")]
        Natural,

        /// <summary>
        /// Enum Manmade for value: manmade
        /// </summary>
        [EnumMember(Value = "manmade")]
        Manmade
    }

}
