/*
 * Nominatim Open API Spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: blake.rogan@outlook.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = HomeScreen.OpenAPI.Nominatim.Client.FileParameter;
using OpenAPIDateConverter = HomeScreen.OpenAPI.Nominatim.Client.OpenAPIDateConverter;

namespace HomeScreen.OpenAPI.Nominatim.Model
{
    /// <summary>
    /// Defines OutputFormat
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OutputFormat
    {
        /// <summary>
        /// Enum Xml for value: xml
        /// </summary>
        [EnumMember(Value = "xml")]
        Xml,

        /// <summary>
        /// Enum Json for value: json
        /// </summary>
        [EnumMember(Value = "json")]
        Json,

        /// <summary>
        /// Enum Jsonv2 for value: jsonv2
        /// </summary>
        [EnumMember(Value = "jsonv2")]
        Jsonv2,

        /// <summary>
        /// Enum Geojson for value: geojson
        /// </summary>
        [EnumMember(Value = "geojson")]
        Geojson,

        /// <summary>
        /// Enum Geocodejson for value: geocodejson
        /// </summary>
        [EnumMember(Value = "geocodejson")]
        Geocodejson
    }

}
