packages:
  - HomeScreen.Web.Config/**
  - HomeScreen.Web.Common/**
  - HomeScreen.Web.Dashboard/**
  - HomeScreen.Web.Slideshow/**

catalogs:
  api:
    '@pinia/colada': ^0.17.6
    '@types/luxon': ^3.7.1
    luxon: ^3.7.2
    zod: ^4.1.12
  build:
    '@tsconfig/node22': ^22.0.2
    '@types/node': ^24.8.1
    '@vitejs/plugin-vue': ^6.0.1
    '@vue/tsconfig': ^0.8.1
    autoprefixer: ^10.4.21
    globals: ^16.4.0
    vite: ^7.1.11
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-dts: ^4.5.4
    vue-tsc: ^3.1.1
  devtools:
    '@cpsoinos/vite-plugin-http2-proxy': ^0.1.0
    vite-plugin-vue-devtools: ^8.0.3
  icons:
    '@fortawesome/free-brands-svg-icons': ^7.1.0
    '@fortawesome/free-regular-svg-icons': ^7.1.0
    '@fortawesome/free-solid-svg-icons': ^7.1.0
    '@fortawesome/vue-fontawesome': ^3.1.2
  mapping:
    '@turf/turf': ^7.2.0
    '@types/geojson': ^7946.0.16
    '@vue-leaflet/vue-leaflet': ^0.10.1
    geojson: ^0.5.0
    leaflet: ^1.9.4
  misc:
    '@tediousjs/connection-string': ^1.0.0
    uuid: ^13.0.0
    web-streams-polyfill: ^4.2.0
  random:
    '@types/seedrandom': ^3.0.8
    seedrandom: ^3.0.5
  storybook:
    '@chromatic-com/storybook': 5.0.0-next.1
    '@storybook/addon-essentials': 9.0.0-alpha.12
    '@storybook/addon-interactions': 9.0.0-alpha.10
    '@storybook/addon-links': ^9.1.13
    '@storybook/blocks': 9.0.0-alpha.17
    '@storybook/test': 9.0.0-alpha.2
    '@storybook/vue3': ^9.1.13
    '@storybook/vue3-vite': ^9.1.13
    storybook: ^9.1.13
  test:
    '@types/jsdom': ^27.0.0
    jsdom: ^27.0.1
    vitest: ^3.2.4
  tools:
    '@biomejs/biome': 2.2.6
    '@hey-api/openapi-ts': ^0.85.2
    npm-run-all2: ^8.0.4
    rimraf: ^6.0.1
    typescript: ^5.9.3
  ui:
    '@tailwindcss/vite': ^4.1.14
    '@yeger/vue-masonry-wall': ^5.1.1
    animate.css: ^4.1.1
    daisyui: ^5.3.7
    tailwindcss: ^4.1.14
  vue:
    vue: ^3.5.22
    vue-router: ^4.6.3
  vueuse:
    '@vueuse/components': ^13.9.0
    '@vueuse/core': ^13.9.0
    '@vueuse/integrations': ^13.9.0
    '@vueuse/motion': ^3.0.3
    async-validator: ^4.2.5
    change-case: ^5.4.4
    drauu: ^0.4.3
    focus-trap: ^7.6.5
    fuse.js: ^7.1.0
    idb-keyval: ^6.2.2
    jwt-decode: ^4.0.0
    nprogress: ^0.2.0
    qrcode: ^1.5.4
    sortablejs: ^1.15.6
    universal-cookie: ^8.0.1

cleanupUnusedCatalogs: true

disallowWorkspaceCycles: true

executionEnv:
  nodeVersion: 22.20.0

linkWorkspacePackages: deep

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@homescreen/*'

preferWorkspacePackages: true

useNodeVersion: 22.20.0
